//
//  AppSplashViewController.m
//  Generated by AppStudio
//

#import "AppSplashViewController.h"
#import "AppAdManager.h"
#import "UIColor+Hex.h"

@interface AppSplashViewController ()

@property (nonatomic, copy, nullable) void (^completion)(void);
@property (nonatomic, assign, getter=hasCompleted) BOOL completed;
@property (nonatomic, strong) CAGradientLayer *backgroundGradient;

@end

@implementation AppSplashViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    [self setupViews];
}

- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
    self.backgroundGradient.frame = self.view.bounds;
}

- (void)startWithCompletion:(void (^)(void))completion {
    self.completion = completion;
    [[AppAdManager sharedManager] showSplashAdFromViewController:self completion:^{
        [self completeSplash];
    }];
}

- (void)completeSplash {
    if (self.hasCompleted) {
        return;
    }

    self.completed = YES;
    if (self.completion) {
        self.completion();
        self.completion = nil;
    }
}

- (void)setupViews {
    self.view.backgroundColor = [UIColor colorWithHex:@"#7C3AED"];

    self.backgroundGradient = [CAGradientLayer layer];
    self.backgroundGradient.colors = @[
        (__bridge id)[UIColor colorWithHex:@"#7C3AED"].CGColor,
        (__bridge id)[UIColor colorWithHex:@"#EC4899"].CGColor
    ];
    self.backgroundGradient.startPoint = CGPointMake(0.0, 0.0);
    self.backgroundGradient.endPoint = CGPointMake(1.0, 1.0);
    [self.view.layer addSublayer:self.backgroundGradient];

    UIView *orbTop = [self glowOrbWithColor:[UIColor colorWithHex:@"#67E8F9"] alpha:0.22];
    orbTop.translatesAutoresizingMaskIntoConstraints = NO;
    [self.view addSubview:orbTop];

    UIView *orbBottom = [self glowOrbWithColor:[[UIColor colorWithHex:@"#FFFFFF"] colorWithAlphaComponent:0.10] alpha:1.0];
    orbBottom.translatesAutoresizingMaskIntoConstraints = NO;
    [self.view addSubview:orbBottom];

    UIImageView *iconView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"BrandMark"]];
    iconView.translatesAutoresizingMaskIntoConstraints = NO;
    iconView.contentMode = UIViewContentModeScaleAspectFit;
    [self.view addSubview:iconView];

    UILabel *titleLabel = [[UILabel alloc] init];
    titleLabel.translatesAutoresizingMaskIntoConstraints = NO;
    titleLabel.text = @"云屿计算器";
    titleLabel.textColor = [UIColor colorWithHex:@"#FFFFFF"];
    titleLabel.font = [UIFont systemFontOfSize:34 weight:UIFontWeightBold];
    titleLabel.textAlignment = NSTextAlignmentCenter;
    titleLabel.numberOfLines = 2;
    [self.view addSubview:titleLabel];

    [NSLayoutConstraint activateConstraints:@[
        [orbTop.widthAnchor constraintEqualToConstant:220.0],
        [orbTop.heightAnchor constraintEqualToConstant:220.0],
        [orbTop.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor constant:-72.0],
        [orbTop.topAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.topAnchor constant:-44.0],

        [orbBottom.widthAnchor constraintEqualToConstant:260.0],
        [orbBottom.heightAnchor constraintEqualToConstant:260.0],
        [orbBottom.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor constant:96.0],
        [orbBottom.bottomAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.bottomAnchor constant:110.0],

        [iconView.centerXAnchor constraintEqualToAnchor:self.view.centerXAnchor],
        [iconView.centerYAnchor constraintEqualToAnchor:self.view.centerYAnchor constant:-48.0],
        [iconView.widthAnchor constraintEqualToConstant:108.0],
        [iconView.heightAnchor constraintEqualToConstant:108.0],

        [titleLabel.topAnchor constraintEqualToAnchor:iconView.bottomAnchor constant:22.0],
        [titleLabel.leadingAnchor constraintGreaterThanOrEqualToAnchor:self.view.leadingAnchor constant:32.0],
        [titleLabel.trailingAnchor constraintLessThanOrEqualToAnchor:self.view.trailingAnchor constant:-32.0],
        [titleLabel.centerXAnchor constraintEqualToAnchor:self.view.centerXAnchor],
    ]];
}

- (UIView *)glowOrbWithColor:(UIColor *)color alpha:(CGFloat)alpha {
    UIView *view = [[UIView alloc] init];
    view.backgroundColor = [color colorWithAlphaComponent:alpha];
    view.layer.cornerRadius = 130.0;
    return view;
}

@end
